'use client';

import { useState } from 'react';
import { useCartStore, CartItem } from '@/store/cart';
import { Button } from '@/components/ui/Button';
import { ShoppingBag, Check, Minus, Plus } from 'lucide-react';
import { cn } from '@/lib/utils';

interface AddToCartButtonProps {
  product: {
    id: string;
    name: string;
    slug: string;
    price: number;
    compareAtPrice?: number | null;
    image?: string | null;
    inventory?: number;
  };
  variant?: {
    id: string;
    size?: string | null;
    color?: string | null;
    inventory?: number;
  } | null;
  selectedSize?: string | null;
  selectedColor?: string | null;
  className?: string;
  showQuantity?: boolean;
}

export function AddToCartButton({
  product,
  variant,
  selectedSize,
  selectedColor,
  className,
  showQuantity = true,
}: AddToCartButtonProps) {
  const [quantity, setQuantity] = useState(1);
  const [isAdded, setIsAdded] = useState(false);
  const addItem = useCartStore((state) => state.addItem);
  const openCart = useCartStore((state) => state.openCart);

  const maxQuantity = variant?.inventory ?? product.inventory ?? 10;
  const isOutOfStock = maxQuantity <= 0;

  const handleAddToCart = () => {
    if (isOutOfStock) return;

    const cartItem: Omit<CartItem, 'quantity'> & { quantity: number } = {
      id: '', // Will be generated by store
      productId: product.id,
      variantId: variant?.id || null,
      name: product.name,
      slug: product.slug,
      image: product.image || null,
      price: product.price,
      compareAtPrice: product.compareAtPrice || null,
      size: selectedSize || variant?.size || null,
      color: selectedColor || variant?.color || null,
      maxQuantity,
      quantity,
    };

    addItem(cartItem);

    // Show added feedback
    setIsAdded(true);
    setTimeout(() => setIsAdded(false), 2000);

    // Open cart drawer
    openCart();

    // Reset quantity
    setQuantity(1);
  };

  return (
    <div className={cn('space-y-4', className)}>
      {/* Quantity Selector */}
      {showQuantity && !isOutOfStock && (
        <div className="flex items-center gap-4">
          <span className="text-sm font-medium text-brand-black">Quantity</span>
          <div className="flex items-center border border-brand-grey-200 rounded-lg">
            <button
              onClick={() => setQuantity((q) => Math.max(1, q - 1))}
              disabled={quantity <= 1}
              className="p-3 hover:bg-brand-grey-50 transition-colors disabled:opacity-50"
              aria-label="Decrease quantity"
            >
              <Minus className="w-4 h-4" />
            </button>
            <span className="w-12 text-center font-medium">{quantity}</span>
            <button
              onClick={() => setQuantity((q) => Math.min(maxQuantity, q + 1))}
              disabled={quantity >= maxQuantity}
              className="p-3 hover:bg-brand-grey-50 transition-colors disabled:opacity-50"
              aria-label="Increase quantity"
            >
              <Plus className="w-4 h-4" />
            </button>
          </div>
          {maxQuantity < 10 && (
            <span className="text-sm text-brand-grey-500">
              Only {maxQuantity} left
            </span>
          )}
        </div>
      )}

      {/* Add to Cart Button */}
      <Button
        onClick={handleAddToCart}
        disabled={isOutOfStock}
        size="lg"
        className={cn(
          'w-full transition-all',
          isAdded && 'bg-green-600 hover:bg-green-700'
        )}
      >
        {isOutOfStock ? (
          'Out of Stock'
        ) : isAdded ? (
          <>
            <Check className="w-5 h-5 mr-2" />
            Added to Bag!
          </>
        ) : (
          <>
            <ShoppingBag className="w-5 h-5 mr-2" />
            Add to Bag
          </>
        )}
      </Button>
    </div>
  );
}
